version: '3.8'
services:
    php-apache:
        container_name: vsnippet-sqli-secound-order-33
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db-mysql
        volumes:
            - ./vsnippet:/var/www/html/
        ports:
            - "127.0.0.1:1337:80"
    db-mysql:
        container_name: vsnippet-db-mysql-sqli-secound-order-33
        volumes:
            - ./config/mysql.sql:/docker-entrypoint-initdb.d/mysql.sql
        image: mysql
        restart: always
        environment:
            MYSQL_DATABASE: "${MYSQL_DATABASE}"
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
        ports:
            - "127.0.0.1:1338:3306"
secrets:
    mysql_database:
        file: ./secrets/MYSQL_DATABASE
    mysql_user:
        file: ./secrets/MYSQL_USER
    mysql_password:
        file: ./secrets/MYSQL_PASSWORD
    mysql_root_password:
        file: ./secrets/MYSQL_ROOT_PASSWORD