[supervisord]
user=${SUPERVISOR_USER}
nodaemon=true
logfile=${SUPERVISOR_LOGFILE}
logfile_maxbytes=50MB
pidfile=/run/supervisord.pid

[program:golang-http]
command=go run /app/5-broken-auth-spoof.go
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
