version: '3.8'
services:
    php-apache:
        container_name: vsnippet-sqli-column-24
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db-mysql
        volumes:
            - ./vsnippet:/var/www/html/
        ports:
            - "127.0.0.1:1337:80"
    db-mysql:
        container_name: vsnippet-db-mysql-sqli-column-24
        volumes:
            - ./config/mysql.sql:/docker-entrypoint-initdb.d/mysql.sql
        image: mysql
        restart: always
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD_FILE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD_FILE}
        ports:
            - "127.0.0.1:1338:3306"
secrets:
    mysql_password:
        file: ./secrets/mysql_password.txt
    mysql_root_password:
        file: ./secrets/mysql_root_password.txt"