version: '3.8'
services:
    node-express:
        container_name: vsnippet-sqli-login-20
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db-mysql
        volumes:
            - ./vsnippet:/var/www/html/
        ports:
            - "127.0.0.1:1337:1337"
    db-mysql:
        container_name: vsnippet-db-mysql-sqli-login-20
        volumes:
            - ./config/mysql.sql:/docker-entrypoint-initdb.d/mysql.sql
        image: mysql
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: /run/secrets/mysql_password
            MYSQL_ROOT_PASSWORD: /run/secrets/mysql_root_password
        secrets:
            - mysql_password
            - mysql_root_password
        ports:
            - "127.0.0.1:1338:3306"
secrets:
    mysql_password:
        file: ./secrets/mysql_password.txt
    mysql_root_password:
        file: ./secrets/mysql_root_password.txt